#ifndef ENUMS_H
#define ENUMS_H

enum GameModes {
    GAME_MODE_0,
    GAME_MODE_1,
    GAME_MODE_2,
    GAME_MODE_3,
    GAME_MODE_4,
    GAME_MODE_PLAYER_SELECTION,
    GAME_MODE_BATTLE_AARON,
    GAME_MODE_BATTLE_DEMITRON,
    GAME_MODE_BATTLE_DEMONICA,
    GAME_MODE_BATTLE_EVE,
    GAME_MODE_BATTLE_GORE,
    GAME_MODE_BATTLE_CHARACTER_5,
    GAME_MODE_BATTLE_MORHIX,
    GAME_MODE_BATTLE_NIIKI,
    GAME_MODE_BATTLE_SCARLET,
    GAME_MODE_BATTLE_SONORK,
    GAME_MODE_BATTLE_ZENMURON,
    GAME_MODE_17,
    GAME_MODE_18,
    GAME_MODE_19,
    GAME_MODE_20,
    GAME_MODE_21,
    GAME_MODE_22,
    GAME_MODE_23,
    GAME_MODE_24,
    GAME_MODE_25,
    GAME_MODE_26,
    GAME_MODE_27,
    GAME_MODE_28,
    GAME_MODE_29,
    GAME_MODE_30,
    GAME_MODE_31,
    GAME_MODE_32,
    GAME_MODE_LOGO,
    GAME_MODE_34,
    GAME_MODE_35,
    GAME_MODE_36,
    GAME_MODE_37
};

// TODO: make enum

#define INP_L 0x0001
#define INP_A 0x0002
#define INP_R 0x0004
#define INP_B 0x0008

#define INP_CUP 0x0010
#define INP_CRIGHT 0x0020
#define INP_CDOWN 0x0040
#define INP_CLEFT 0x0080

#define INP_ZTRIG 0x0100
#define INP_START 0x0800

#define INP_UP 0x1000
#define INP_RIGHT 0x2000
#define INP_DOWN 0x4000
#define INP_LEFT 0x8000

#define INP_DIRECTION (INP_UP | INP_RIGHT | INP_DOWN | INP_LEFT)

enum AssetContext { CONTEXT_2000 = 0x2000, CONTEXT_EEFF = 0xEEFF };

enum CharacterIds {
    AARON = 0,
    DEMITRON = 1,
    DEMONICA = 2,
    EVE = 3,
    GORE = 4,
    CHARACTER_5 = 5,
    MORPHIX = 6,
    NIIKI = 7,
    SCARLET = 8,
    SONORK = 9,
    ZENMURON = 10,
    NUM_CHARACTERS = 11
};

enum Players { PLAYER_1 = 0, PLAYER_2 = 1 };

enum ObjectFlags { OBJ_FLAG_4000000 = 0x4000000 };

#endif
